name: 'Rebase to solve simple conflicts'
on:
  push:
    branches:
      - development
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: abaicus/rebase@master
        with:
          github_token: ${{secrets.GH_TOKEN}}
